
name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{secrets.PRIVATE_KEY}}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/deployment/apps/assessment-sejuta-cita
            git pull origin development
            git status
            npm install
            pm2 restart 0